// Phase 1 of the UX revamp: the welcome screen asks one focused
// question — "what are you working on?" — and answers it with a
// concrete shortlist of methods generated by AI.
//
// Phase 5 layer: sign-in is now required to receive a shortlist
// (verified email via magic link). The project name + description
// the user typed are saved to the persisted store BEFORE the magic
// link is sent, so the email-verification round-trip doesn't drop
// them. When the user returns signed in with a pending project, the
// AI analysis fires automatically and they land on the shortlist.
import { useEffect, useState } from 'react'
import { useShallow } from 'zustand/react/shallow'
import { useStore } from '../store/useStore'
import { ScrappyButton, ScrappyChip } from '../components/ScrappyButton'
import { suggestMethods, hasMistral } from '../lib/mistral'
import { hasSupabase, sendMagicLink } from '../lib/supabase'

const INK = '#1C2530'
const YELLOW = '#FFC83D'
const TEAL = '#14B8A6'
const CORAL = '#FB7185'

// ── Decorative ink strokes — kept; they're part of the brand. ──
function InkCorners() {
  return (
    <>
      <svg viewBox="0 0 220 220"
        style={{
          position: 'absolute', top: -20, left: -40,
          width: 240, height: 240,
          zIndex: 0, pointerEvents: 'none',
        }}>
        <path d="M -10 70 C 30 30, 90 60, 110 110 S 70 200, 30 220"
          fill="none" stroke={INK} strokeWidth="14" strokeLinecap="round" />
      </svg>
      <svg viewBox="0 0 220 220"
        style={{
          position: 'absolute', bottom: -20, right: -40,
          width: 240, height: 240,
          zIndex: 0, pointerEvents: 'none',
        }}>
        <path d="M 230 150 C 190 190, 130 160, 110 110 S 150 20, 190 0"
          fill="none" stroke={INK} strokeWidth="14" strokeLinecap="round" />
      </svg>
    </>
  )
}

export function WelcomeView() {
  const {
    userEmail,
    setProjectContext, setAiSuggestions,
    goProjectFit, goMap, goDashboard,
    ensureDefaultTeam,
    aiSuggestions, projectContext,
  } = useStore(useShallow(s => ({
    userEmail:         s.userEmail,
    setProjectContext: s.setProjectContext,
    setAiSuggestions:  s.setAiSuggestions,
    goProjectFit:      s.goProjectFit,
    goMap:             s.goMap,
    goDashboard:       s.goDashboard,
    ensureDefaultTeam: s.ensureDefaultTeam,
    aiSuggestions:     s.aiSuggestions,
    projectContext:    s.projectContext,
  })))

  const [name, setName] = useState(projectContext?.name || '')
  const [desc, setDesc] = useState(projectContext?.desc || '')
  const [email, setEmail] = useState('')
  const [busy, setBusy] = useState(false)
  const [err,  setErr]  = useState('')
  // 'idle' | 'sending' | 'sent' — drives the auth gate UI when the
  // user clicks the primary CTA without being signed in.
  const [magicStatus, setMagicStatus] = useState('idle')
  // Cooldown (in seconds) until the user can request another magic
  // link. Supabase OTP throttles per-email — without a UI countdown
  // people repeatedly tap the button and pile up rate-limit errors.
  const [cooldown, setCooldown] = useState(0)

  // Tick the cooldown down to zero.
  useEffect(() => {
    if (cooldown <= 0) return
    const id = setTimeout(() => setCooldown(c => c - 1), 1000)
    return () => clearTimeout(id)
  }, [cooldown])

  // Auth gating. When Supabase is configured we require a verified
  // email before running the AI analysis. When it isn't, the welcome
  // falls back to the previous anonymous flow so dev / preview
  // builds still work.
  const authGated = hasSupabase && !userEmail

  const descReady = desc.trim().length >= 20
  const emailValid = /\S+@\S+\.\S+/.test(email.trim())
  const canSubmit = descReady && hasMistral && !busy && cooldown === 0
    && (!authGated || emailValid || magicStatus === 'sent')

  // Run the AI analysis. Assumes the project is already in the store
  // (callers must call setProjectContext before this).
  const runAnalysis = async ({ pName, pDesc }) => {
    setBusy(true); setErr('')
    try {
      const out = await suggestMethods({ name: pName, desc: pDesc })
      if (!out.length) throw new Error('No matching methods returned. Try rephrasing.')
      setAiSuggestions(out)
      ensureDefaultTeam()
      goProjectFit()
    } catch (e2) {
      setErr(e2?.message || 'Analysis failed. Try again in a moment.')
    } finally {
      setBusy(false)
    }
  }

  const submit = async (e) => {
    e?.preventDefault?.()
    if (busy) return
    if (cooldown > 0) return
    if (!descReady) {
      setErr('A few sentences would help — what is the project about, where, who is it for?')
      return
    }
    if (!hasMistral) {
      setErr('AI is not configured on this build. Use the catalogue link below.')
      return
    }
    const pName = name.trim() || 'Your project'
    const pDesc = desc.trim()
    // Persist the project FIRST so it survives the magic-link
    // round-trip. Also clear any stale shortlist so the auto-resume
    // useEffect actually fires for the new project (otherwise the
    // user re-enters with an unrelated old shortlist still cached).
    setProjectContext({ name: pName, desc: pDesc })
    setAiSuggestions([])

    if (authGated) {
      if (!emailValid) {
        setErr('Enter a valid email — we send a one-tap sign-in link.')
        return
      }
      setMagicStatus('sending'); setErr('')
      try {
        await sendMagicLink(email.trim())
        setMagicStatus('sent')
        // Conservative cooldown — Supabase's per-email OTP limit
        // is around 60 s. We arm the countdown so the resend
        // button doesn't pile up rate-limit errors.
        setCooldown(60)
      } catch (err2) {
        // Log the full error to the console so we can inspect the
        // status / code Supabase returned (the displayed message
        // alone often hides whether it's the per-email cooldown
        // or the project-wide hourly cap).
        console.warn('[welcome] sendMagicLink error:', err2)
        const msg    = err2?.message || ''
        const status = err2?.status ?? err2?.statusCode ?? null
        const code   = err2?.code   ?? null
        // Per-email security cooldown: Supabase tells us how long
        // to wait. Hourly project cap: message has no number, just
        // "email rate limit exceeded".
        const m       = msg.match(/(\d+)\s*seconds?/i)
        const cdown   = m ? parseInt(m[1], 10) : 0
        const isHourly = /rate limit (?:reached|exceeded)/i.test(msg)
                       && cdown === 0
        const isCool   = cdown > 0
        setMagicStatus('idle')
        setCooldown(isCool ? cdown : 0)
        if (isHourly) {
          setErr(
            `Supabase hourly email cap reached — the built-in email service is limited to ~2 sends/hour, ` +
            `regardless of plan. Add a custom SMTP provider in Supabase Dashboard → Authentication → ` +
            `Emails (Resend / SendGrid / SES / Postmark) to raise it. ` +
            (status ? `[${status}] ` : '') + (code ? `(${code}) ` : '') +
            msg
          )
        } else if (isCool) {
          setErr(
            `Per-email cooldown — wait ${cdown}s before requesting another link. ` +
            `Your project is saved; the button will re-arm itself.`
          )
        } else {
          setErr(
            (status ? `[${status}] ` : '') + (code ? `(${code}) ` : '') +
            (msg || 'Could not send the link. Try again.')
          )
        }
      }
      return
    }
    await runAnalysis({ pName, pDesc })
  }

  // Auto-resume after the user clicks the magic-link in their email
  // and the SPA reloads them as signed-in. They land back on the
  // welcome screen with `projectContext` still in the persisted
  // store but `aiSuggestions` empty — fire the analysis they asked
  // for instead of making them retype + click again.
  useEffect(() => {
    if (!hasSupabase) return
    if (!userEmail) return
    if (busy) return
    if (!projectContext?.desc) return
    if (aiSuggestions.length > 0) return
    runAnalysis({
      pName: projectContext.name || 'Your project',
      pDesc: projectContext.desc,
    })
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [userEmail])


  const skipToBrowse = () => {
    ensureDefaultTeam()
    goMap()
  }

  return (
    <div className="anim-fadein" style={{
      position: 'relative',
      minHeight: '100vh',
      padding: '40px 22px 32px',
      overflow: 'hidden',
    }}>
      <InkCorners />

      <div style={{
        position: 'relative', zIndex: 1,
        maxWidth: 460, margin: '0 auto',
      }}>
        {/* ── Wordmark + tagline ───────────────────── */}
        <div style={{ textAlign: 'center', marginTop: 24, marginBottom: 18 }}>
          <div style={{
            fontFamily: 'Barlow Condensed, Impact, sans-serif',
            fontWeight: 900,
            fontSize: 'clamp(56px,18vw,88px)',
            color: INK, lineHeight: .92,
            letterSpacing: '.005em',
          }}>
            ReCity
          </div>
          <div style={{
            fontFamily: '-apple-system, Helvetica Neue, sans-serif',
            fontSize: 14, color: '#3F3A36',
            marginTop: 14, lineHeight: 1.45,
            maxWidth: 360, margin: '14px auto 0',
          }}>
            What's your urban project?
            <br/>We'll pick the right methods to use.
          </div>
        </div>

        {/* ── The one input card — name + description + CTA ── */}
        <form onSubmit={submit}
          style={{
            background: '#FFFFFF', borderRadius: 18, padding: 18,
            border: `2.5px solid ${INK}`,
            marginBottom: 16,
            display: 'flex', flexDirection: 'column', gap: 12,
          }}>
          <div>
            <label style={LABEL}>Project name <span style={OPT}>(optional)</span></label>
            <input style={INP}
              placeholder="e.g. Lyon Part-Dieu redesign"
              value={name} onChange={e => setName(e.target.value)} />
          </div>
          <div>
            <label style={LABEL}>What are you working on?</label>
            <textarea
              placeholder="A few sentences about the site, the ambition, the constraints, who it's for…"
              value={desc} onChange={e => setDesc(e.target.value)}
              rows={5}
              style={{ ...INP, resize: 'vertical', lineHeight: 1.45 }} />
            <div style={{
              fontSize: 10, color: '#9C958A', marginTop: 4,
              fontFamily: 'Barlow Condensed, Impact, sans-serif',
              letterSpacing: '.04em', textTransform: 'uppercase',
            }}>
              {desc.trim().length < 20
                ? `${20 - desc.trim().length} more characters before we can analyse`
                : '✓ ready to analyse'}
            </div>
          </div>
          {/* Email gate — appears when Supabase is configured and the
              user is not signed in. We require a verified email before
              an AI shortlist is generated; the project is saved to the
              persisted store before the magic-link is sent so the
              email round-trip doesn't lose what they typed. */}
          {authGated && magicStatus !== 'sent' && (
            <div>
              <label style={LABEL}>Your email <span style={OPT}>(we'll send a one-tap sign-in link)</span></label>
              <input style={INP} type="email" required
                placeholder="you@example.com"
                value={email} onChange={e => setEmail(e.target.value)} />
              <div style={{
                fontSize: 10, color: '#9C958A', marginTop: 4, lineHeight: 1.4,
              }}>
                We keep your project name and description while you check
                your inbox — when you click the link the shortlist is
                generated automatically.
              </div>
            </div>
          )}

          {/* Magic-link sent — confirmation panel, replaces the email
              field once the link is on its way. Shows a cooldown
              countdown so the user knows when they can resend, plus
              an "I clicked the link, generate now" fallback for the
              case where the auto-resume useEffect didn't fire. */}
          {authGated && magicStatus === 'sent' && (
            <div style={{
              padding: '10px 12px',
              background: '#E6F4EC', border: `1.5px solid #10B981`,
              borderRadius: 10, fontSize: 12, color: '#1F4E32', lineHeight: 1.45,
            }}>
              <div style={{
                fontFamily: 'Barlow Condensed, Impact, sans-serif',
                fontWeight: 900, fontSize: 11, letterSpacing: '.06em',
                textTransform: 'uppercase', marginBottom: 4,
              }}>✓ Check your email</div>
              We sent a one-tap link to <b>{email}</b>. Click it to
              come back here — your shortlist will generate automatically.
              <div style={{
                marginTop: 8, display: 'flex', flexWrap: 'wrap', gap: 12,
              }}>
                <button type="button"
                  onClick={() => { if (cooldown === 0) submit() }}
                  disabled={cooldown > 0 || busy}
                  style={{
                    background: 'transparent', border: 'none',
                    cursor: cooldown === 0 ? 'pointer' : 'default',
                    padding: 0,
                    fontFamily: 'Barlow Condensed, Impact, sans-serif',
                    fontWeight: 900, fontSize: 10,
                    color: cooldown === 0 ? '#1F4E32' : '#9CB6A4',
                    letterSpacing: '.06em', textTransform: 'uppercase',
                    textDecoration: cooldown === 0 ? 'underline' : 'none',
                  }}>
                  {cooldown > 0 ? `Resend in ${cooldown}s` : '↻ Resend link'}
                </button>
                <button type="button"
                  onClick={() => { setMagicStatus('idle'); setCooldown(0) }}
                  style={{
                    background: 'transparent', border: 'none',
                    cursor: 'pointer', padding: 0,
                    fontFamily: 'Barlow Condensed, Impact, sans-serif',
                    fontWeight: 900, fontSize: 10, color: '#1F4E32',
                    letterSpacing: '.06em', textTransform: 'uppercase',
                    textDecoration: 'underline',
                  }}>· Different email</button>
              </div>
            </div>
          )}

          {/* Signed-in returning user — no email gate, just a status
              chip. If the auto-resume useEffect already kicked off,
              the form is "busy" and the button label says "ANALYSING…".
              Otherwise the user can click GENERATE manually. */}
          {hasSupabase && userEmail && (
            <div style={{
              padding: '8px 10px',
              background: '#FFFDF8', border: `1.5px solid ${INK}33`,
              borderRadius: 10,
            }}>
              <div style={{
                fontFamily: 'Barlow Condensed, Impact, sans-serif',
                fontWeight: 900, fontSize: 10,
                color: '#5A5550', letterSpacing: '.06em',
                textTransform: 'uppercase',
              }}>✓ Signed in as {userEmail}</div>
            </div>
          )}

          {err && (
            <div style={{
              padding: '8px 10px',
              background: '#FCE8E2', border: `1.5px solid #C0452A`,
              borderRadius: 8, fontSize: 12, color: '#7A1F0E', lineHeight: 1.4,
            }}>{err}</div>
          )}
          {magicStatus !== 'sent' && (
            <ScrappyButton type="submit"
              onClick={submit}
              color={canSubmit ? YELLOW : '#E0DAD2'}
              size="lg" full>
              {busy ? 'ANALYSING…'
                : magicStatus === 'sending' ? 'SENDING LINK…'
                : cooldown > 0 ? `WAIT ${cooldown}S TO RETRY`
                : authGated ? '✨ EMAIL ME MY SHORTLIST →'
                : '✨ GET MY METHOD SHORTLIST →'}
            </ScrappyButton>
          )}
        </form>

        {/* If a previous shortlist exists, surface it explicitly */}
        {aiSuggestions.length > 0 && projectContext && (
          <button onClick={goProjectFit}
            style={{
              width: '100%', padding: '10px 12px', marginBottom: 16,
              background: 'transparent',
              border: `1.5px dashed ${INK}55`, borderRadius: 10,
              cursor: 'pointer', textAlign: 'left',
            }}>
            <div style={{
              fontFamily: 'Barlow Condensed, Impact, sans-serif',
              fontWeight: 900, fontSize: 10, color: '#5A5550',
              letterSpacing: '.06em', textTransform: 'uppercase',
            }}>Continue your last project</div>
            <div style={{
              fontFamily: 'Barlow Condensed, Impact, sans-serif',
              fontWeight: 900, fontSize: 14, color: INK,
              marginTop: 2,
            }}>{projectContext.name} — {aiSuggestions.length} methods picked →</div>
          </button>
        )}

        {/* ── Secondary doors ─────────────────────── */}
        <div style={{
          textAlign: 'center', marginTop: 6,
        }}>
          <button onClick={skipToBrowse}
            style={{
              background: 'transparent', border: 'none', cursor: 'pointer',
              fontFamily: 'Barlow Condensed, Impact, sans-serif',
              fontWeight: 900, fontSize: 12,
              color: '#5A5550', letterSpacing: '.05em',
              textTransform: 'uppercase',
              padding: '6px 12px',
            }}>
            Or browse all 133 methods →
          </button>
          {userEmail && (
            <button onClick={() => { ensureDefaultTeam(); goDashboard() }}
              style={{
                background: 'transparent', border: 'none', cursor: 'pointer',
                fontFamily: 'Barlow Condensed, Impact, sans-serif',
                fontWeight: 900, fontSize: 12,
                color: '#5A5550', letterSpacing: '.05em',
                textTransform: 'uppercase',
                padding: '6px 12px', marginLeft: 4,
              }}>
              · Open my dashboard
            </button>
          )}
        </div>

        {/* ── Tiny credibility strip — kept low-key ── */}
        <div style={{
          display: 'flex', justifyContent: 'center', gap: 8,
          marginTop: 28, flexWrap: 'wrap',
        }}>
          <ScrappyChip color={YELLOW} size="sm">133 methods</ScrappyChip>
          <ScrappyChip color={TEAL}   size="sm">4 phases</ScrappyChip>
          <ScrappyChip color={CORAL}  size="sm">6 lenses</ScrappyChip>
        </div>
      </div>
    </div>
  )
}

const LABEL = {
  fontFamily: 'Barlow Condensed, Impact, sans-serif',
  fontWeight: 900,
  fontSize: 11, letterSpacing: '.06em', textTransform: 'uppercase',
  color: INK, display: 'block', marginBottom: 6,
}
const OPT = {
  color: '#9C958A', fontWeight: 700, fontSize: 10,
  textTransform: 'none', letterSpacing: 0,
}
const INP = {
  width: '100%', padding: '11px 14px',
  borderRadius: 12,
  border: `2.5px solid ${INK}`,
  background: '#FFFFFF',
  color: INK, fontSize: 14, outline: 'none',
  fontFamily: '-apple-system, Helvetica Neue, sans-serif', fontWeight: 600,
  boxSizing: 'border-box',
}
